language: swift
os: osx
osx_image: xcode9.2

# cache:
#   - cocoapods
#   - slather


env:
   global:
   - LANG=en_US.UTF-8
   - MACOS_SCHEME="Mayon"
   - MACOS_SDK=macosx10.12

   
script:
  ./Scripts/build
